services:
  planer-rc:
    
    container_name: nightec/planer-rc
    ports:
      - "8124:80"
    restart: always
    # Limity zasobów
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: '0.2'
        reservations:
          memory: 10M