apiVersion: apps/v1
kind: Deployment
metadata:
  name: planer-rc
  labels:
    app: planer-rc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planer-rc
  template:
    metadata:
      labels:
        app: planer-rc
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - planer-rc
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: planer-rc
        image: nightec/planer-rc:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "10Mi"
          limits:
            memory: "50Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: planer-rc-service
spec:
  type: NodePort
  selector:
    app: planer-rc
  ports:
  - protocol: TCP
    port: 8124
    targetPort: 80
    nodePort: 30124
