apiVersion: apps/v1
kind: Deployment
metadata:
  name: planer-rc
  labels:
    app: planer-rc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planer-rc
  template:
    metadata:
      labels:
        app: planer-rc
    spec:
      containers:
      - name: planer-rc
        image: nightec/planer-rc:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "10Mi"
          limits:
            memory: "50Mi"
            cpu: "200m"
